# Generated by Django 4.2.7 on 2025-07-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_category_alter_ticket_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='office_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
