# Generated by Django 4.2.7 on 2025-07-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_userprofile_office_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('New', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('unresolved', 'Unresolved'), ('closed', 'Closed')], default='New', max_length=20),
        ),
    ]
